In [861]:
## Teste

%load_ext autoreload
%autoreload
%reset -f

from src import Node as nd
from src import Bar as bar
from src import Frame
from src import Beam as vg
from src import Analysis
from src import Apoio as ap
from src import CargaPontual as cp
from src import CargaDistribuida as cd
from src import Modelo as md

import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [862]:
## Propriedades do material

mod_elast = 25e9
mod_trans = 7e9

## Propriedades da seção

b = 0.2
h = 0.4
area = b * h
Iy = b * h ** 3 / 12
Iz = h * b ** 3 / 12
Ix = Iy + Iz

In [863]:
# nd.Node.clear_list_nodes()
# bar.Barra.clear_list_bars()

# node1 = nd.Node(0, 0, 0)
# node2 = nd.Node(2.5, 0, 0)
# node3 = nd.Node(5, 0, 0)
# node4 = nd.Node(5, 2.5, 0)
# node5 = nd.Node(5, 5, 0)
# node6 = nd.Node(2.5, 5, 0)
# node7 = nd.Node(0, 5, 0)
# node8 = nd.Node(0, 2.55, 0)

In [864]:
## Definindo os apoios:

# apoio1 = ap.Apoio([[0, 1], [0, 1], [0, 1]], node = node1)
# apoio2 = ap.Apoio([[0, 1], [0, 1], [0, 1]], node = node3)
# apoio3 = ap.Apoio([[0, 1], [0, 1], [0, 1]], node = node5)
# apoio4 = ap.Apoio([[0, 1], [0, 1], [0, 1]], node = node7)

In [865]:
## Definindo as cargas:

# carga1 = cp.CargaPontual(0, 0, -10e3, 0, 0, 0, node=node2)
# carga2 = cp.CargaPontual(0, 0, -10e3, 0, 0, 0, node=node4)
# carga3 = cp.CargaPontual(0, 0, -10e3, 0, 0, 0, node=node6)
# carga4 = cp.CargaPontual(0, 0, -10e3, 0, 0, 0, node=node8)

In [866]:
## Definindo as barras:

# frame1 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node1, node2)
# frame2 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node2, node3)
# frame3 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node3, node4)
# frame4 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node4, node5)
# frame5 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node5, node6)
# frame6 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node6, node7)
# frame7 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node7, node8)
# frame8 = Frame.Frame(area, Ix, Iy, Iz, mod_elast, mod_trans, node8, node1)

In [867]:
# modelo = Analysis.Analysis(frame1, frame2, frame3, frame4, frame5, frame6, frame7, frame8)
# modelo.solver()

In [868]:
# print(frame1.vetor_esforcos)
# print(frame2.vetor_esforcos)

In [869]:
# print(frame3.vetor_esforcos)
# print(frame4.vetor_esforcos)

In [870]:
# teste_2d = ap.Apoio3([0, 0, 1])

In [871]:
# print(frame5.vetor_esforcos)
# print(frame6.vetor_esforcos)

In [872]:
# print(frame7.vetor_esforcos)
# print(frame8.vetor_esforcos)

In [873]:
# print(frame1.vetor_deslocamentos)
# print(frame2.vetor_deslocamentos)

In [874]:
# print(frame3.vetor_deslocamentos)
# print(frame4.vetor_deslocamentos)

In [875]:
# print(frame5.vetor_deslocamentos)
# print(frame6.vetor_deslocamentos)

In [876]:
# print(frame7.vetor_deslocamentos)
# print(frame8.vetor_deslocamentos)

In [877]:
# frame3.vetor_esforcos

In [878]:
# modelo.calcular_matriz_rigidez()
# modelo.k_global

In [879]:
# print("foo")
# modelo.calcular_vetor_deslocamentos()
# modelo.vetor_deslocamentos

In [880]:
# modelo.calcular_vetor_forcas()
# modelo.vetor_forcas

In [881]:
# modelo.calcular_solucao()
# modelo.vetor_deslocamentos.shape

In [882]:
nd.Node.clear_list_nodes()
bar.Barra.clear_list_bars()

node11 = nd.Node3(0, 0)
node12 = nd.Node3(2.5, 0)
node13 = nd.Node3(5, 0)

In [883]:
apoio11 = ap.Apoio3([0, 0, 1], node = node11)
apoio13 = ap.Apoio3([0, 0, 1], node = node13)


In [884]:
carga11 = cp.CargaPontual3(0, -10e3, 0, node = node12)

In [885]:
vars(node11)

{'indice': 1,
 'lista_graus': [1, 2, 3, 4, 5, 6],
 'x': 0,
 'y': 0,
 'z': 0,
 'fx': 0,
 'fy': 0,
 'fz': 0,
 'mx': 0,
 'my': 0,
 'mz': 0,
 'forces_vector': array([0, 0, 0, 0, 0, 0]),
 'ux': 0,
 'uy': 0,
 'uz': 0,
 'rx': 0,
 'ry': 0,
 'rz': nan,
 'displacement_vector': array([ 0.,  0.,  0.,  0.,  0., nan])}

In [886]:
bar11 = Frame.Frame2D(area, Iy, mod_elast, node11, node12)
bar12 = Frame.Frame2D(area, Iy, mod_elast, node12, node13)

In [887]:
vars(bar11)

{'lista_cargas': [],
 'list_nodes': [<src.Node.Node3 at 0x1bf22f14680>,
 'theta_x': 1.0,
 'theta_y': 0.0,
 'theta_z': 0.0,
 'rotate': 0,
 'ke_': Matrix([
 [ 800000000.0,          0,           0,                     0,                0,                    0, -800000000.0,          0,           0,                     0,                0,                    0],
 [           0,  2.048e+16,           0,                     0,                0,             2.56e+16,            0, -2.048e+16,           0,                     0,                0,             2.56e+16],
 [           0,          0,  20480000.0,                     0,      -25600000.0,                    0,            0,          0, -20480000.0,                     0,      -25600000.0,                    0],
 [           0,          0,           0,  1.06666666666667e+25,                0,                    0,            0,          0,           0, -1.06666666666667e+25,                0,                    0],
 [           0,   

In [888]:
viga2 = Analysis.Analysis(bar11, bar12)
viga2.solver()

In [889]:
viga2.k_global

Matrix([
[ 800000000.0,          0,           0,                     0,                0,                    0, -800000000.0,          0,           0,                     0,                0,                    0,            0,          0,           0,                     0,                0,                    0],
[           0,  2.048e+16,           0,                     0,                0,             2.56e+16,            0, -2.048e+16,           0,                     0,                0,             2.56e+16,            0,          0,           0,                     0,                0,                    0],
[           0,          0,  20480000.0,                     0,      -25600000.0,                    0,            0,          0, -20480000.0,                     0,      -25600000.0,                    0,            0,          0,           0,                     0,                0,                    0],
[           0,          0,           0,  1.06666666666667e+25,     

In [890]:
viga2.k_global[4, 4]

42666666.6666667

In [891]:
viga2.vetor_forcas

array([     0.,      0.,      0.,      0.,      0.,      0.,      0.,
       -10000.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.])

In [892]:
viga2.vetor_deslocamentos

array([ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        0.000000e+00, -5.859375e-13,  0.000000e+00, -9.765625e-13,
        0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
        0.000000e+00,  5.859375e-13])

In [893]:
viga2.k_shorted.shape

(8, 8)

In [894]:
viga2.f_shorted

[0.0, 0.0, -10000.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [895]:
import sympy

sympy.Matrix(viga2.k_shorted)

Matrix([
[4.26666666666667e+16,            0, -2.56e+16,          0,                    0,                0, 2.13333333333333e+16,                    0],
[                   0, 1600000000.0,         0,          0,                    0,                0,                    0,                    0],
[           -2.56e+16,            0, 4.096e+16,          0,                    0,                0,                    0,             2.56e+16],
[                   0,            0,         0, 40960000.0,                    0,                0,                    0,                    0],
[                   0,            0,         0,          0, 2.13333333333333e+25,                0,                    0,                    0],
[                   0,            0,         0,          0,                    0, 85333333.3333334,                    0,                    0],
[2.13333333333333e+16,            0,         0,          0,                    0,                0, 8.53333333333334e+16,

In [896]:
bar11.vetor_esforcos

array([0, 5000.00000000000, 0, 0, 0, 0, 0, -5000.00000000000, 0, 0, 0,
       12500.0000000000], dtype=object)

In [897]:
bar12.vetor_esforcos

array([0, -5000.00000000000, 0, 0, 0, -12500.0000000000, 0,
       5000.00000000000, 0, 0, 0, 0], dtype=object)